rvm: 2.2
sudo: required
services: docker
cache: bundler
env:
  matrix:
    - DIST=ubuntu-trusty
    - DIST=ubuntu-precise
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.yml
before_install:
  - curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.9.0
install:
  - chef exec bundle install
script:
  - travis_retry chef exec bundle exec kitchen verify default-$DIST