---
- name: Add repository for google chrome
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    update_cache: yes
- name: Add key for google chrome
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
- name: Update apt packages
  apt:
    update_cache: "yes"
    upgrade: "dist"
  become: yes

- name: Install essential packages
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - ssh
    - wget
    - curl
    - build-essential
    - git
    - unzip
    - tmux
    - xsel
    - language-pack-ja
    - google-chrome-stable
    - htop